/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package navirebizerte;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

/**
 *
 * @author ASUS
 */
public class agent extends javax.swing.JFrame {

    /**
     * Creates new form agent
     */
    Connection con;
    Statement s;
    ResultSet r;
    DefaultTableModel model=new DefaultTableModel();

    public agent() {
        DbConnect db = new DbConnect();
        con = db.connect();
        initComponents();
        model.addColumn("Id");
        model.addColumn("Nom");
model.addColumn("Prenom");
model.addColumn("Adresse");
model.addColumn("NumeroTel");
model.addColumn("NumeroFax");
model.addColumn("Email");
try
{
model.setRowCount(0);
s=con.createStatement();
ResultSet Rs= s.executeQuery("Select * from agentconsignataire");
while(Rs.next())
{
model.addRow(new Object[]{Rs.getString("reference"),Rs.getString("nom"),Rs.getString("prenom"),Rs.getString("adresse"),Rs.getString("numeroTel"),Rs.getString("numeroFax"),Rs.getString("email")});
}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(rootPane, e);
}
agentsTable.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastNameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        numeroTelField = new javax.swing.JTextField();
        adresseField = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        researchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeroFaxField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agentsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Consignataire");
        setPreferredSize(new java.awt.Dimension(900, 520));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(lastNameField);
        lastNameField.setBounds(10, 70, 140, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 54));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 20, 20);

        idField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idField.setForeground(new java.awt.Color(0, 0, 54));
        idField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idField.setText("Entrer Id");
        getContentPane().add(idField);
        idField.setBounds(170, 420, 130, 40);
        getContentPane().add(emailField);
        emailField.setBounds(10, 250, 300, 30);
        getContentPane().add(numeroTelField);
        numeroTelField.setBounds(10, 190, 140, 30);
        getContentPane().add(adresseField);
        adresseField.setBounds(10, 130, 300, 30);

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 54));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        editBtn.setText("Modifier");
        editBtn.setBorderPainted(false);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn);
        editBtn.setBounds(170, 320, 130, 40);

        researchBtn.setBackground(new java.awt.Color(255, 255, 255));
        researchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        researchBtn.setForeground(new java.awt.Color(0, 0, 54));
        researchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/research.png"))); // NOI18N
        researchBtn.setText("Rechercher");
        researchBtn.setBorderPainted(false);
        researchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                researchBtnMouseClicked(evt);
            }
        });
        researchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                researchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(researchBtn);
        researchBtn.setBounds(30, 420, 130, 40);

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 54));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        addBtn.setText("Ajouter");
        addBtn.setBorderPainted(false);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(30, 320, 130, 40);

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 54));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        deleteBtn.setText("Supprimer");
        deleteBtn.setBorderPainted(false);
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(30, 370, 130, 40);

        refreshBtn.setBackground(new java.awt.Color(255, 255, 255));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(0, 0, 54));
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        refreshBtn.setText("Actualiser");
        refreshBtn.setBorderPainted(false);
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBtnMouseClicked(evt);
            }
        });
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshBtn);
        refreshBtn.setBounds(170, 370, 130, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 140, 14);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numéro de Fax");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 170, 140, 14);
        getContentPane().add(numeroFaxField);
        numeroFaxField.setBounds(170, 190, 140, 30);
        getContentPane().add(firstNameField);
        firstNameField.setBounds(170, 70, 140, 30);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nom");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 50, 80, 14);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numéro de Téléphone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 140, 14);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adresse");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 70, 14);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prénom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 50, 80, 14);

        agentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prénom", "Adresse", "Numéro de Téléphone", "Numéro de Fax", "Email"
            }
        ));
        agentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(agentsTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 70, 500, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg4_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 0, 940, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void refresh(){
DefaultTableModel newModel=new DefaultTableModel();
newModel.addColumn("Id");
newModel.addColumn("Nom");
newModel.addColumn("Prenom");
newModel.addColumn("Adresse");
newModel.addColumn("NumeroTel");
newModel.addColumn("NumeroFax");
newModel.addColumn("Email");
try
{
model.setRowCount(0);
s=con.createStatement();
ResultSet Rs= s.executeQuery("Select * from agentconsignataire");
while(Rs.next())
{
newModel.addRow(new Object[]{Rs.getInt("reference"),Rs.getString("nom"),Rs.getString("prenom"),Rs.getString("adresse"),Rs.getString("numeroTel"),Rs.getString("numeroFax"),Rs.getString("email")});
}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(rootPane, e);
}
model = newModel;
agentsTable.setModel(model);
}
private void deplace(int i)
{
try
{
lastNameField.setText(model.getValueAt(i,1).toString());
firstNameField.setText(model.getValueAt(i,2).toString());
adresseField.setText(model.getValueAt(i,3).toString());
numeroTelField.setText(model.getValueAt(i,4).toString());
numeroFaxField.setText(model.getValueAt(i,5).toString());
emailField.setText(model.getValueAt(i,6).toString());
idField.setText(model.getValueAt(i,0).toString());
}
catch(Exception e)
{
System.err.println(e);
JOptionPane.showMessageDialog(null,"erreur de deplacement "+e.getLocalizedMessage());
}
}
    private void researchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_researchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_researchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        
String firstName = firstNameField.getText();
String lastName= lastNameField.getText();
String email = emailField.getText();
String adresse = adresseField.getText();
int numeroTel = Integer.parseInt(numeroTelField.getText());
int numeroFax = Integer.parseInt(numeroFaxField.getText());
try
{
PreparedStatement stmt1 = con.prepareStatement("insert into agentconsignataire(nom, prenom, adresse, numeroTel, numeroFax, email)VALUES(?, ?, ?, ?, ?, ?)");
stmt1.setString(1, lastName);
stmt1.setString(2, firstName);
stmt1.setString(3, adresse);
stmt1.setInt(4, numeroTel);
stmt1.setInt(5, numeroFax);
stmt1.setString(6, email);
stmt1.executeUpdate();
JOptionPane.showMessageDialog(null,"l'agent " + firstName + " " + lastName + " a été bien ajouté!");
numeroTelField.setText("");
lastNameField.setText("");
firstNameField.setText("");
adresseField.setText("");
numeroFaxField.setText("");
emailField.setText("");
refresh();
}
catch(Exception ex)
{
JOptionPane.showMessageDialog(null, "Une Erreur s'est arrivé lors de l'ajout du agent");
}
    }//GEN-LAST:event_addBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
try
{
int id = Integer.parseInt(idField.getText());
String firstName = firstNameField.getText();
String lastName= lastNameField.getText();
String email = emailField.getText();
String adresse = adresseField.getText();
int numeroTel = Integer.parseInt(numeroTelField.getText());
int numeroFax = Integer.parseInt(numeroFaxField.getText());
if(JOptionPane.showConfirmDialog(null,"Confirmer la modification","modification",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
{
PreparedStatement stmt = con.prepareStatement("UPDATE agentconsignataire SET nom=?, prenom=?, adresse=?, numeroTel=?, numeroFax=?, email=? Where reference=?");
stmt.setString(1, lastName);
stmt.setString(2, firstName);
stmt.setString(3, adresse);
stmt.setInt(4, numeroTel);
stmt.setInt(5, numeroFax);
stmt.setString(6, email);
stmt.setInt(7, id);
stmt.executeUpdate();
}

}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"erreur de modification!!"+e.getMessage());
System.err.println(e);
}        
refresh();
    }//GEN-LAST:event_editBtnMouseClicked

    private void agentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentsTableMouseClicked
       try
{
int i =agentsTable.getSelectedRow();
deplace(i);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,"erreur de deplacement "+e.getLocalizedMessage());
}
    }//GEN-LAST:event_agentsTableMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        try
{
if (JOptionPane.showConfirmDialog(null,"attention vous allez supprimer un agent, est ce que tu et sure?","supprimer agent",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
if(idField.getText().length()!=0)
{
s.executeUpdate("Delete From agentconsignataire where reference = " + idField.getText());
refresh();
}
else
{
JOptionPane.showMessageDialog(null,"veuillez SVP remplir le champ Id!");
}
}
}
catch (Exception e)
{
JOptionPane.showMessageDialog(null,"error lors de la supression de l'agent: \n"+e.getMessage());
}
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void refreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMouseClicked
        refresh();
    }//GEN-LAST:event_refreshBtnMouseClicked

    private void researchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchBtnMouseClicked
        try
{
model.setRowCount(0);
{
r=s.executeQuery("Select * From agentconsignataire WHERE reference = '"+idField.getText()+"'");

 }

 while(r.next())
{
Object [] etudiant={r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getInt(6),r.getString(7)};
model.addRow(etudiant);
}
if (model.getRowCount()==0){JOptionPane.showMessageDialog(null,"il y a aucun agent");}
else{
int i=0;
deplace(i);
}

 }
catch(Exception e)
{
System.err.println(e);
JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_researchBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                welcome back = new welcome();
                back.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField adresseField;
    private javax.swing.JTable agentsTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField numeroFaxField;
    private javax.swing.JTextField numeroTelField;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton researchBtn;
    // End of variables declaration//GEN-END:variables
}
