/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package navirebizerte;

/**
 *
 * @author ASUS
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        agentBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        escaleBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenue");
        setPreferredSize(new java.awt.Dimension(450, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bienvenue");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(150, 150, 140, 29);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(110, 190, 210, 20);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 54));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/city-dock.png"))); // NOI18N
        jButton7.setText("Poste d'accostage");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(120, 400, 190, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/boat.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 150, 130);

        agentBtn.setBackground(new java.awt.Color(255, 255, 255));
        agentBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agentBtn.setForeground(new java.awt.Color(0, 0, 54));
        agentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/call-center-operator.png"))); // NOI18N
        agentBtn.setText("Agent Consignataire");
        agentBtn.setBorderPainted(false);
        agentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agentBtnMouseClicked(evt);
            }
        });
        agentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(agentBtn);
        agentBtn.setBounds(220, 340, 190, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 54));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registered.png"))); // NOI18N
        jButton4.setText("Registre Lloyd");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 340, 190, 40);

        escaleBtn.setBackground(new java.awt.Color(255, 255, 255));
        escaleBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        escaleBtn.setForeground(new java.awt.Color(0, 0, 54));
        escaleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/escalator (1).png"))); // NOI18N
        escaleBtn.setText("Escale");
        escaleBtn.setBorderPainted(false);
        escaleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escaleBtnMouseClicked(evt);
            }
        });
        escaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escaleBtnActionPerformed(evt);
            }
        });
        getContentPane().add(escaleBtn);
        escaleBtn.setBounds(20, 280, 190, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 54));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/growth.png"))); // NOI18N
        jButton5.setText("Marchandise");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 280, 190, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 54));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admin.png"))); // NOI18N
        jButton3.setText("Employe");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 220, 190, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 54));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user (2).png"))); // NOI18N
        jButton1.setText("Armateur");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 220, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 460, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                employer employerPage= new employer();
                employerPage.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void agentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentBtnActionPerformed
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agent agentPage= new agent();
                agentPage.setVisible(true);
            }
        });        
    }//GEN-LAST:event_agentBtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void escaleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escaleBtnMouseClicked

    }//GEN-LAST:event_escaleBtnMouseClicked

    private void agentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentBtnMouseClicked

    }//GEN-LAST:event_agentBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                armateur armateurPage= new armateur();
                armateurPage.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void escaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escaleBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                escale escalePage= new escale();
                escalePage.setVisible(true);
            }
        });
    }//GEN-LAST:event_escaleBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                marchandise marchandisePage= new marchandise();
                marchandisePage.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                registre registrePage= new registre();
                registrePage.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                poste postePage= new poste();
                postePage.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agentBtn;
    private javax.swing.JButton escaleBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
